package com.example.template.ux.main

enum class Screen(val title: String) {
    HOME("Template"),
    ANIMATED_GESTURE("Animated Gesture"),
    BOTTOM_NAVIGATION("Bottom Navigation"),
    BOTTOM_SHEET("Bottom Sheet"),
    CAROUSEL("Carousel"),
    CHILD_WITH_NAVIGATION("Child with Navigation"),
    CHIP_SHEET("Chip Sheet"),
    DATE_TIME_FORMAT("Date/Time Format"),
    DIALOG("Dialog"),
    FLIPPABLE("Flippable"),
    GMAIL_ADDRESS_FIELD("Gmail Address Field"),
    IMAGE_PICKER("Image Picker"),
    INPUT_EXAMPLES("Input Examples"),
    KTOR("Ktor Test"),
    MODAL_BOTTOM_SHEET("Modal Bottom Sheet"),
    NAVIGATION_PAGER("Navigation Pager"),
    NOTIFICATION_PERMISSIONS("Permissions (Notification)"),
    PAGER("Pager"),
    PANNING_ZOOMING("Panning and Zooming"),
    PARAMETERS("Parameters"),
    PERMISSIONS("Permissions (Location)"),
    POP_WITH_RESULT("Pop With Result"),
    PULL_REFRESH("Pull Refresh"),
    REORDERABLE_LIST("Reorderable List"),
    SEARCH("Search"),
    SIDE_DRAWER("Side Drawer"),
    SNACKBAR("Snackbar"),
    STICKY_HEADERS("Sticky Headers"),
    SWIPABLE("Swipable"),
    SYSTEM_UI("System UI"),
    TABS("Tabs"),
    URI_NAVIGATION("Uri Navigation"),
    VIDEO("Video"),
    WEBVIEW("Webview");
}